apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fofwpargocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ivarbergman/fofwpargocd.git
    targetRevision: HEAD
    path: fofwpargocd
  destination:
    server: https://kubernetes.default.svc
    namespace: fofwpargocd
